"use client"

import '../globals.css'
import { Poppins } from 'next/font/google'
import Provider from '../context/AuthContext'
import ToasterContext from '../context/ToasterContext'
import Header from './components/Header'
import Footer from './components/Footer'
import Admin from './Admin/page'


const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function adminLayout() {
  return (
    <>
      <html lang="en">
          <body className={poppins.className}>
            <div className='max-w-7xl mx-auto px-5'>
                <Provider>
                  <ToasterContext />
                  <Header />
                  <Admin />
                  <Footer />
                </Provider>
            </div>
          </body>
        </html>
      </>
  )  
}